name: gmm-env-1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9 # Because d2l package fails to install on later versions
  - pip
  - pytorch
  - torchvision
  - ipykernel # For jupyter notebooks
# Extra:
#  - mxnet
#  - jax
#  - tensorflow
  - pip:
    - d2l
    - ucimlrepo # Download sample datasets
    - openimages # week-1
    - scikit-image # week-1
    - transformers # week-2