name: gmm-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9 # Because d2l package fails to install on later versions
  - pip
  - pytorch
  - torchvision
  - ipykernel # For jupyter notebooks
# Extra:
#  - mxnet
#  - jax
#  - tensorflow
  - pip:
    - d2l
    - ucimlrepo